FROM node:14
MAINTAINER  pradeep  pradeep.pyc@gmail.com
RUN mkdir /app
WORKDIR /app
# copy cypress code from host to container
COPY . /app
RUN apt-get update
RUN apt-get install -y --no-install-recommends libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
#RUN apt-get install -y wget
#RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
RUN npm install cypress
RUN npm install
RUN cd kontent-sample-app-vue/
RUN npm install
RUN npm run serve &
RUN sleep 120
RUN cd ../
RUN /app/node_modules/cypress/bin/cypress verify
RUN /app/node_modules/cypress/bin/cypress run --spec /app/cypress/integration/local.feature
CMD ["node", "/app/cypress/plugins/cr2.j"]
